### ISSUE TITLE
RuntimeError: The size of tensor a (108) must match the size of tensor b (212) at non-singleton dimension 0

### ISSUE THREAD

**Issue by demongolem-biz** [dolphin-zs/Doc2EDAG#28]
Out of the box, I try to run run_dee_task.py and I get the above error.  The only thing I changed was when I got this:

> Traceback (most recent call last):
  File "run_dee_task.py", line 10, in <module>
    from dee.dee_task import DEETask, DEETaskSetting
  File "/home/gregory.werner/Doc2EDAG/dee/dee_task.py", line 11, in <module>
    from .dee_helper import logger, DEEExample, DEEExampleLoader, DEEFeatureConverter, \
  File "/home/gregory.werner/Doc2EDAG/dee/dee_helper.py", line 14, in <module>
    from .ner_task import NERExample, NERFeatureConverter
  File "/home/gregory.werner/Doc2EDAG/dee/ner_task.py", line 14, in <module>
    from .ner_model import BertForBasicNER, judge_ner_prediction
  File "/home/gregory.werner/Doc2EDAG/dee/ner_model.py", line 15, in <module>
    class BertForBasicNER(PreTrainedBertModel):
NameError: name 'PreTrainedBertModel' is not defined

I exchange BertPreTrainedModel for PreTrainedBertModel

**Comment by WangYao-GoGoGo** [comment]
I have the similar problem.

The size of tensor a (11) must match the size of tensor b (22) at non-singleton dimension 0


`loss = self.model(
                doc_batch_dict, features, use_gold_span=use_gold_span, train_flag=True, teacher_prob=teacher_prob
            )`
